### ISSUE TITLE
Forked repo not showing "develop" branch

### ISSUE THREAD

**Issue by michelle-wms** [UBC-MDS/DSCI_522_GROUP3_COFFEERATINGS#28]
Hello guys, need some help here- 
I've accepted Arlin's PR into develop branch, and then when I refresh my forked repo (see picture), there's nothing to fetch upstream. By right, it should show there's now a new branch?
Do I need to reclone this whole repo again? Thanks.
<img width="633" alt="Capture" src="https://user-images.githubusercontent.com/34495572/143374722-185bec73-fc80-4eed-8228-3232b26f67eb.PNG">

**Comment by arlincherian** [comment]
Hi Michelle, you should be able to see 2 branches within the UBC-MDS/DSCI_522_GROUP3_COFFEERATING rep
![Screen Shot 2021-11-24 at 7 35 09 PM](https://user-images.githubusercontent.com/77990545/143375511-ccbc97be-819e-46f2-bfa8-4c5889b4da3c.png)
o. My forked repo also only says 1 branch. Once you push your work to your forked repo, then you can send a pull request to the develop branch. I hope that makes sense? Maybe Berkay can help with this.

**Comment by khbunyan** [comment]
Don't worry too much about having things up to date on the dev branch. It's just there so you can pull the code you are reviewing to your own comp and test before making any REAL changes to the main.

If you're happy with Arlin's changes, then she should make another pull request but this time to the main branch.

**Comment by michelle-wms** [comment]
Thanks all! Had a call with Berkay. It's resolved.

**Comment by michelle-wms** [comment]
However, that opens up another question: @berkaybulut You mentioned, everyone works off 'develop' branch all the way, and don't touch main until submission time and one person just PR to the main branch. But then the TA won't be able to see everyone's PR right? If only just one person does the final merge at end of week. So, we should all do it the way @khbunyan  mentioned above -- whereby on the fly- once someone else approves the develop work, then open PR again to the main branch. Correct?

**Comment by berkaybulut** [comment]
I think it got too complicated with develop and main. We can remove it if you want to.. I dont think team's life shoudl be more difficult. We may face issues later in the next two weeks for not having a develop - hopefully no conflicts and big errors that we will have to roll back git and things.

**Comment by michelle-wms** [comment]
Hmm.. personally, I think yes it's alright to just have the main branch to make life easier for this project -- I know in real life production though, that's probably the best way to do things!

**Comment by michelle-wms** [comment]
@arlincherian @khbunyan should we remove the 'develop' branch?

**Comment by michelle-wms** [comment]
Hi, we all agree that everyone will just push to main branch now on. Thanks!
