### ISSUE TITLE
README info needed PART 1: USAGE

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/DSCI_522_GROUP3_COFFEERATINGS#37]
Hi Everyone, can you all please send me the following for your respective sections **by Friday Morning.**
I've given examples here from Tiffany's repo. Please send your usage for your script like the below:

# download data (@khbunyan and @arlincherian )
python src/download_data.py --out_type=feather --url=http://mlr.cs.umass.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data --out_file=data/raw/wdbc.feather

# pre-process data  (@khbunyan )
Rscript src/pre_process_wisc.r --input=data/raw/wdbc.feather --out_dir=data/processed 

# create exploratory data analysis figure and write to file  (@berkaybulut )
Rscript src/eda_wisc.r --train=data/processed/training.feather --out_dir=results

# Model analysis (@michelle-wms and @arlincherian )
Rscript src/fit_breast_cancer_predict_model.r --train=data/processed/training.feather --out_dir=results

**Comment by michelle-wms** [comment]
**For script 4**: python src/ml_analysis.py --train="data/processed/train_df.csv" --test="data/processed/test_df.csv" --table_file="results/model_comparison.csv" --image1_file="results/feature_importance_rfr_plot.png" --image2_file="results/feature_importance_rfc_plot.png"

**Comment by arlincherian** [comment]
For rendering final report: Rscript -e "rmarkdown::render('reports/coffee_rating_prediction_report.rmd', output_format = 'html_document')"

**Comment by khbunyan** [comment]
Thanks both, just need the EDA script @berkaybulut and this section is complete
