### ISSUE TITLE
README info needed PART 2: Dependencies

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/DSCI_522_GROUP3_COFFEERATINGS#38]
Hi all, can you please send me the dependencies for your scripts **by friday morning**?

Thank you, responding here is fine.

**Comment by arlincherian** [comment]
Hi Kristin, 

Here are a few I have used in the scripts for analysis and R packages that will be required for Rmd. @michelle-wms, feel free to add on to this if I have missed anything:

Dependencies 

OS level 
Python ==3.9.5
R version =4.1.1 

Python Packages:
Pandas ==1.3.3
Seaborn ==0.11.2
scikit-learn ==1.0 
numpy ==1.21.2

R packages
Knitr=1.36

**Comment by khbunyan** [comment]
Thank you, @berkaybulut do you have dependencies to add?
