### ISSUE TITLE
Dataset to use: Arabica

### ISSUE THREAD

**Issue by arlincherian** [UBC-MDS/DSCI_522_GROUP3_COFFEERATINGS#4]
Hi Team, 

We will be using the cleaned arabica dataset for this project. The robusta coffee dataset only has 28 rows, so we are just sticking with the arabica one.

**Comment by michelle-wms** [comment]
Hi Arlin! Just to clarify - is this just 1 feature out of the whole dataset? Or it's an entirely different dataset? If it's still within the same dataset, we could keep the original data as "raw dataset" inside the data folder -- and when we do the actual predictive modelling work, we can then dropping those rows? In that way the raw dataset would match the download script as well

**Comment by arlincherian** [comment]
> Hi Arlin! Just to clarify - is this just 1 feature out of the whole dataset? Or it's an entirely different dataset? If it's still within the same dataset, we could keep the original data as "raw dataset" inside the data folder -- and when we do the actual predictive modelling work, we can then dropping those rows? In that way the raw dataset would match the download script as well

Hey! There are two datasets, one on arabica coffee with around 1300 rows and another dataset on robusta coffee with only about 28 rows. So I'm thinking we'll just focus on the first dataset for now since the second one is not that big of a dataset
