### ISSUE TITLE
Double Licenses 

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/DSCI_522_GROUP3_COFFEERATINGS#5]
Hey Team

Just a quick note to let you know that we are confirming which license is the correct one for this dataset. The original one has the MIT but the tidytuesday uses Creative Commons Zero v1.0 Universal. 

We will keep you posted, we are confirming with Tiffany.

Thanks!

**Comment by michelle-wms** [comment]
Hi Kristin,
It's fine to use the MIT one! Other groups are using it as well. Here's from her instructions:
"You may have noticed when you create a new repo on GitHub, you’re asked to set a license for your project. If you do not currently have a preference, we recommend you use the MIT license for your project."

**Comment by khbunyan** [comment]
Thank you! Sounds good, fine for us to use for our dataset.

I still want to confirm which one we should be quoting about the original data set, there is reference to two and I just want to be sure we are referencing the correct one.

**Comment by arlincherian** [comment]
Hi everyone, just heard back from Florencia on this issue. She confirms that we should be using the MIT license on our repo as well. I have added this to the readme file as well.
