### ISSUE TITLE
Plan for analysis discussion

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/DSCI_522_GROUP3_COFFEERATINGS#7]
#pasted from slack

Hi Guys,
I'm getting ready to write the plan analysis this morning for our proposal and I wanted to know what your feelings were on that.
We are doing a predictive question (using python) which means we could do two routes:
regression analysis (with some t-tests etc)
ML model analysis.
What do people prefer?

Michelle: 
I think we can include more techniques, and say we will try both Regression and Classification:
Just for your reference ---
Regression with Ridge, Random Forest Regressor, Decision Tree Regressor, etc. [Target is the coffee points]
Classification with SVC, D Tree, Random Forest, Log Reg, etc. [Target can be binary classification whereby >0.5 = 1, <0.5=0]
Inspect the features and some simple EDA to understand the data
Data cleansing (drop missing values, imputation, etc)
Fit models and do cross validation
Hyperparameter optimization
Model selection via best validation score
Report performance on test dataset

**Comment by khbunyan** [comment]
Sounds like based on what you've written Michelle, you'd like to do an ML route.

Berkay, Arlin, do you have any thoughts on that? Statistical testing vs ML?

**Comment by michelle-wms** [comment]
FYI If you guys want, you could share your project proposal with us on a google doc when you've drafted something and then we can comment/edit/review it!

**Comment by khbunyan** [comment]
Plan for analysis is complete and uploaded to the main repo.
